- generic [ref=e121]:
  - generic [ref=e122]:
    - img [ref=e123]
    - heading "פרופיל" [level=1] [ref=e126]
  - generic [ref=e127]:
    - generic [ref=e128]:
      - generic [ref=e130]: P
      - generic [ref=e131]:
        - paragraph [ref=e132]: Playwright Test
        - paragraph [ref=e133]: riw.test.playwright@gmail.com
    - generic [ref=e134]:
      - generic [ref=e135]:
        - img [ref=e136]
        - paragraph [ref=e139]: מיקום בית
      - paragraph [ref=e140]: משמש כנקודת התחלה במסלולים
      - button "השתמש במיקום הנוכחי (GPS)" [ref=e141] [cursor=pointer]:
        - img [ref=e142]
        - text: השתמש במיקום הנוכחי (GPS)
      - generic [ref=e147]: או הקלד כתובת
      - 'textbox "לדוגמה: \"אפרים 5, תל אביב\"" [ref=e151]'
    - generic [ref=e152]:
      - generic [ref=e153]:
        - img [ref=e154]
        - paragraph [ref=e160]: שיתוף מקלטים
      - paragraph [ref=e161]: שתף מקלטים עם חברים ומשפחה
      - button "פתח שיתוף" [ref=e162] [cursor=pointer]:
        - generic [ref=e163]: פתח שיתוף
        - img [ref=e164]
    - generic [ref=e166]:
      - generic [ref=e167]:
        - img [ref=e168]
        - paragraph [ref=e172]: שפה
      - paragraph [ref=e173]: Hebrew / English
      - button "🇮🇱 עברית Switch to English" [ref=e174] [cursor=pointer]:
        - generic [ref=e175]: 🇮🇱 עברית
        - generic [ref=e176]: Switch to English
    - generic [ref=e177]:
      - generic [ref=e178]:
        - img [ref=e179]
        - paragraph [ref=e182]: שמות ערים
      - paragraph [ref=e183]: כיצד יוצגו הערים במסנן המפה
      - generic [ref=e184]:
        - button "שם מלא קרית ביאליק, קרית ים..." [ref=e185] [cursor=pointer]:
          - generic [ref=e187]:
            - paragraph [ref=e188]: שם מלא
            - paragraph [ref=e189]: קרית ביאליק, קרית ים...
        - button "קיצור ק׳ ביאליק, ק׳ ים..." [ref=e190] [cursor=pointer]:
          - generic [ref=e193]:
            - paragraph [ref=e194]: קיצור
            - paragraph [ref=e195]: ק׳ ביאליק, ק׳ ים...
    - button "יציאה מהחשבון" [ref=e196] [cursor=pointer]:
      - img [ref=e197]
      - text: יציאה מהחשבון
  - navigation "ניווט ראשי" [ref=e200]:
    - link "בית" [ref=e201] [cursor=pointer]:
      - /url: /
      - img [ref=e203]
      - generic [ref=e206]: בית
    - link "מפה" [ref=e207] [cursor=pointer]:
      - /url: /map
      - img [ref=e209]
      - generic [ref=e211]: מפה
    - link "מסלול" [ref=e212] [cursor=pointer]:
      - /url: /route
      - img [ref=e214]
      - generic [ref=e218]: מסלול
    - link "פרופיל" [ref=e219] [cursor=pointer]:
      - /url: /profile
      - img [ref=e222]
      - generic [ref=e225]: פרופיל